import type { Metadata } from "next";
import { Provider } from "./provider";
import { Appbar } from "ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <Appbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}

// type Props = {
//   children: ReactNode;
// };

// export default function RootLayout({ children }: Props) {
//   ...
//   return (
//     ...
//     <NextAuthProvider>
//       ...
//       {children}
//       ...
//     </NextAuthProvider>
//     ...
//   );
// }
